### ISSUE TITLE
How would you access `this.props` in componentWillMount using this library?

### ISSUE THREAD

**Issue by EwanValentine** [JamieDixon/react-lifecycle-component#3]
I've had a little play with this library, I really like the idea. However, I'd expect to be able to access props somehow, for example... 

```
const componentWillMount = () => {
  const { actions, param } = this.props // ??
  actions.getIr(params.id)
}
```

**Comment by JamieDixon** [comment]
Hi Ewan,

Glad you like the idea and thanks for taking time to write.

Since `connectWithLifecycle` picks up your `componentWillMount` function from `props`, you will already be in a position to access the other props being passed along.

For example:

```
const mapStateToProps = (state, ownProps) {
 const actions = bindActionCreators(ownProps.someActions);
 return {
  actions,
  componentWillMount: () => {
   actions.getIr(ownProps.id);
  }
}
}
```

Do you have an example where this isn't the case? (`mapDispatchToProps` could be but there's always `mergeProps` if you need it) 

I didn't want to pass in the props to the lifecycle functions directly because we'd be breaking the standard interface.

In all honesty I'm not 100% sure how useful this lib is. I used it a lot at first but over the last few months I've found it to be an unnecessary abstraction and using a `class` is more idiomatic.

**Comment by JamieDixon** [comment]
This issue is now fixed as per https://github.com/JamieDixon/react-lifecycle-component/releases/tag/2.0.4 

We're now calling each lifecycle method with the context of the wrapping component so that `this.props` works.
