### ISSUE TITLE
support for react 16.0.0

### ISSUE THREAD

**Issue by DonGiulio** [JamieDixon/react-lifecycle-component#8]
Hello, after upgrading to react 16.0.0 I get the following warning with react-lifecycle-component: 2.0.5:

npm WARN react-lifecycle-component@2.0.5 requires a peer of react@^0.14.0 || ^15.0.0-0 but none is installed. You must install peer dependencies yourself.

**Comment by JamieDixon** [comment]
Thanks for raising this issue @DonGiulio.

Off the top of my head, there's just 2 pieces to do to support React 16.

1. Add React 16.x.x to the package.json
2. Add `componentDidCatch` to the lifecycle hooks supported.

I'd be happy to take a PR on this one if you've got time.

**Comment by DonGiulio** [comment]
I'm afraid my experience in JS is not that broad to do it on my own, 

I'd love to do a PR but I'd need some guidance.
no probs with the obvious one (# 1) but for # 2 I'd do a mess

**Comment by JamieDixon** [comment]
I'd be happy to help @DonGiulio 

Firstly you'll want to change the `react` `peerDependency` in package.json. This package will work with any version greater than 0.14.0 so it's probably best to replace the value with `>= ^0.14.0`. This should cover us for React 16.

The second part will be some small changes to `/src/component.js` notably:

1) Add `componentDidCatch` to the `propTypes`.
2) Add a `componentDidCatch` method to the class body like the others lifecycle methods:

```
componentDidCatch(error, info) {
   this.execute(this.props.componentDidCatch, [error, info]);
}
```

3) In the `render` method of the same file, add `componentDidCatch` to the destructuring assignment so that it's not passed on to `<Comp />`

```
const {
    componentDidCatch, <--- Here
    componentWillMount,
    componentDidMount,
    componentWillReceiveProps,
    componentWillUpdate,
    componentDidUpdate,
    componentWillUnmount,
    shouldComponentUpdate,
    ...realProps
} = this.props;
```

If you're happy to do this and confident enough with git to raise a PR, that would be great. Feel free to ask if you'd like further assistance.

**Comment by DonGiulio** [comment]
opened a PR, I hope there are no troubles about it?

**Comment by JamieDixon** [comment]
Thanks @DonGiulio I'll take a look at it today 👍

**Comment by EwiththeBowtie** [comment]
I believe this issue was closed with this PR:
#9

**Comment by JamieDixon** [comment]
Thanks @EwiththeBowtie
